site_name: TaskList Docs
site_description: Documentación de TaskList, una app sencilla de lista de tareas
site_author: Jose Juventino Castillo

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.tabs.link

nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Guía de uso: guia-de-uso.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
